version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-donaciones
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: donaciones
      MYSQL_USER: appuser
      MYSQL_PASSWORD: app1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
